// https://rust-exercises.com/100-exercises/04_traits/11_clone
// 
// TODO: add the necessary `Clone` implementations (and invocations)
//  to get the code to compile.
//
// Remember that you can use 
// $> cargo expand
// to explore the code generated by derive macros.

pub fn summary(ticket: Ticket) -> (Ticket, Summary) {
    (ticket.clone(), ticket.summary())
}

#[derive(Clone)]
pub struct Ticket {
    pub title: String,
    pub description: String,
    pub status: String,
}

impl Ticket {
    pub fn summary(self) -> Summary {
        Summary {
            title: self.title,
            status: self.status,
        }
    }
}

pub struct Summary {
    pub title: String,
    pub status: String,
}
